const config = {
  symptomes: [
    "Pulsatinf",
    "Sensitivity to light",
    "Sensitivity to sound",
    "Sensitivity to smells",
    "Nausea",
    "Vomiting",
    "Stress",
    "Drowsiness",
    "Dizziness",
    "Vertigo",
    "Tension",
    "Numbness",
    "Visual disturbances",
    "Hallicunations",
    "Blurred visions",
    "Blind spots",
    "Tunnel vision",
    "Aura",
  ],
  locations: [
    "Forehead",
    "Temples",
    "Crown of the head",
    "Left eye",
    "Right eye",
    "Arms",
    "Legs",
    "Neck/shoulder",
    "Sinuses",
    "Jaw",
  ],
  medicions: [
    "Acetaminophen (Tylenol)",
    "Aspirin",
    "Ibuprofen",
    "Naproxen",
    "Triptans",
    "Egrotamines",
    "Opioids",
    "Butalbital-containing medications",
    "Preventiv medications",
    "Antidepressants",
    "Antiepileptic drugs",
    "Botox injections",
    "CGRP monoclonal antibodies",
  ],
};
